ALTER TABLE coupons
ADD COLUMN IF NOT EXISTS max_uses INTEGER DEFAULT NULL CHECK (max_uses IS NULL OR max_uses > 0),
ADD COLUMN IF NOT EXISTS uses_count INTEGER DEFAULT 0 CHECK (uses_count >= 0),
ADD COLUMN IF NOT EXISTS min_order_amount DOUBLE PRECISION DEFAULT NULL CHECK (min_order_amount IS NULL OR min_order_amount >= 0);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS coupon_code TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS discount_amount DOUBLE PRECISION DEFAULT 0;
